# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-22 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='input2',
            field=models.CharField(default='Naah', max_length=300),
        ),
    ]
