# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-22 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_code_input2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='input2',
        ),
    ]
